### PR TITLE
[BUG] Screenshot bugs for 8.2

### PR DESCRIPTION
**Pull request by joepeeples**
Resolves:
- https://github.com/elastic/security-docs/issues/1953
- https://github.com/elastic/security-docs/issues/1954

Previews:
- [Endpoints](https://security-docs_1960.docs-preview.app.elstc.co/guide/en/security/master/admin-page-ov.html) (scroll down to "Integration policy details")
- Create a detection rule ->
   - [Create an indicator match rule](https://security-docs_1960.docs-preview.app.elstc.co/guide/en/security/master/rules-ui-create.html#create-indicator-rule)
   - [Use value lists with indicator match rules](https://security-docs_1960.docs-preview.app.elstc.co/guide/en/security/master/rules-ui-create.html#indicator-value-lists)

For the indicator match rule images, I just cropped out the outdated portions because they weren't relevant to the task being illustrated anyway.

### CODE REVIEW

**Review by benironside — APPROVED** [review]
LGTM!

**Review by nastasha-solomon — APPROVED** [review]
LGTM, thanks!

**Review by karanbirsingh-qasource — APPROVED** [review]
Approved !!

**Comment by deepikakeshav-qasource** [comment]
Hi @joepeeples ,

We tested this PR and found that the changes are correctly done. 

Create a detection rule ->
[Create an indicator match rule](https://security-docs_1960.docs-preview.app.elstc.co/guide/en/security/master/rules-ui-create.html#create-indicator-rule)
[Use value lists with indicator match rules](https://security-docs_1960.docs-preview.app.elstc.co/guide/en/security/master/rules-ui-create.html#indicator-value-lists)

**Screenshot**:
image

image


Thanks!

**Review by deepikakeshav-qasource — APPROVED** [review]

**Review by jmikell821 — APPROVED** [review]
Images LGTM, thanks!

**Pull request merged**
