### PR TITLE
Add 7.13 rules updates

### PR DESCRIPTION
**Pull request by brokensound77**
Add updates for 7.13 prebuilt rules

[prebuilt rule reference](https://security-docs_685.docs-preview.app.elstc.co/guide/en/security/master/prebuilt-rules.html)

### CODE REVIEW

**Comment by jmikell821** [comment]
Hi @brokensound77 - looks like the build failed because there was an invalid reference. 

`INFO:build_docs:asciidoctor: WARNING: invalid reference: powershell-spawning-cmd`

Can you take a look? Thanks!

**Comment by brokensound77** [comment]
> Hi @brokensound77 - looks like the build failed because there was an invalid reference.
> 
> `INFO:build_docs:asciidoctor: WARNING: invalid reference: powershell-spawning-cmd`
> 
> Can you take a look? Thanks!

In troubleshooting this issue I found another issue in the original generation code. I fixed it and regenerated the docs

**Comment by brokensound77** [comment]
I had to manually remove references to deprecated rules from the [Tune detection rules](https://security-docs_685.docs-preview.app.elstc.co/guide/en/security/master/tuning-detection-signals.html) page. I also manually added the deprecated rules to removed in the [prebuilt-rules-changelog](https://security-docs_685.docs-preview.app.elstc.co/guide/en/security/master/prebuilt-rules-changelog.html) (though looks like I need to fix spacing).

Lastly, after fixing the error where new notes and FPs were not getting pulled, I had to manually replace the conflicting markdown (`##`) with asciidocs to just bolded letters (`**`)

**Review by nastasha-solomon — APPROVED** [review]
LGTM!

**Review by bm11100 — APPROVED** [review]
LGTM! Confirmed the changelog has the deprecated rules as well. 🚢

**Pull request merged**
