### PR TITLE
[Request][Serverless & 8.15]: Expandable flyout setting being removed from advanced settings 

### PR DESCRIPTION
**Pull request by nastasha-solomon**
Fixes https://github.com/elastic/security-docs/issues/5291 by removing docs for the `securitySolution:enableExpandableFlyout` advanced setting.

ESS previews:

- [Configure advanced settings](https://security-docs_bk_5292.docs-preview.app.elstc.co/guide/en/security/master/advanced-settings.html)
- [View detection alert details](https://security-docs_bk_5292.docs-preview.app.elstc.co/guide/en/security/master/view-alert-details.html)

Serverless previews:

- [Configure advanced settings](https://docs-elastic-3kgndohw9-elastic-dev.vercel.app/serverless/security/advanced-settings)
- [View detection alert details](https://docs-elastic-3kgndohw9-elastic-dev.vercel.app/serverless/security/view-alert-details)

### CODE REVIEW

**Comment by elasticdocs** [comment]
:rocket: Built _co-preview-docs_ successfully!

* https://docs-elastic-dma0tq89u-elastic-dev.vercel.app

* Built with commit e681f3b1df38820bc294f6eb83878e4cce2ec3f0

> Issues? Visit #next-docs in Slack

**Review by PhilippeOberti — DISMISSED** [review]

**Comment by nastasha-solomon** [comment]
@PhilippeOberti just merged https://github.com/elastic/kibana/pull/184169 today, so the change should be included in next week's Serverless release, which is currently scheduled to begin on **June 10**. 

Notes for merging this PR:
- Before I merge this PR, I need to verify that the `securitySolution:enableExpandableFlyout` advanced setting is no longer visible on the Advanced Settings page in Serverless. It'd also be worth spot-checking areas where the expandable flyout is used, such as Timeline (events and alerts), the Hosts page (host details), and the Users page (user details).
- Make sure to remove Serverless files from the backport PR that's automatically created. 
  NOTE: Might not need to do this if [this PR](https://github.com/elastic/security-docs/pull/5300), which auto-cleans PRs, is merged before I merge this PR.

**Review by natasha-moore-elastic — APPROVED** [review]

**Comment by nastasha-solomon** [comment]
I checked the QA server and confirmed that the `securitySolution:enableExpandableFlyout` setting isnt' available on the Advanced Settings page. Today and tomorrow, I'll watch the Kibana release tracker and periodically check our Canary Prod project to see if this change has been promoted.

**Comment by nastasha-solomon** [comment]
Validated that the change is available on the Prod Canary Server. Dashboard shows that the promotion to Prod Noncanary is complete too, so can merge tomorrow.

**Comment by elasticdocs** [comment]
:rocket: Built _elastic-dot-co-docs-preview-docs_ successfully!

* https://elastic-dot-co-docs-production-rdup8ofbs-elastic-dev.vercel.app

* Built with commit 3443f90011d4fe927710b221d44b024b5bf299a6

> Issues? Visit #next-docs in Slack

**Review by natasha-moore-elastic — APPROVED** [review]

**Pull request merged**
