### PR TITLE
[DOCS] Update Import rules API sample return: new `rules_count` field

### LINKED ISSUE #2073: [DOCS] - Update rules import API sample return
## Description 

Super minor update to the rules import API - the returned data now includes another field `rules_count` which is the total number of rules we calculated a user attempted to import. We used to rely on the errors array + success count to tally this, but that is no longer reliable as the errors can include errors around actions imports (with the rule itself still importing, just without the action if action failure occurs).

## Notes

- PR https://github.com/elastic/kibana/pull/131873

### PR DESCRIPTION
**Pull request by joepeeples**
Resolves #2073.

The Import rules API docs didn't previously include a sample response, so added that entire section (including the `rules_count` field).

Preview: [Import rules (API) | Example response](https://security-docs_2084.docs-preview.app.elstc.co/guide/en/security/master/rules-api-import.html#_example_response_2)

### CODE REVIEW

**Comment by joepeeples** [comment]
@elasticmachine run elasticsearch-ci/docs

**Review by nastasha-solomon — APPROVED** [review]

**Review by jmikell821 — APPROVED** [review]
LGTM! 👍

**Comment by deepikakeshav-qasource** [comment]
Hi @joepeeples  ,

We tested the linked doc and found that doc is correctly updated as per the latest UI. So we are good to go ahead and merge the changes.

**Screenshot:**
image


Marking this ticket as 'QA validated'.

Thanks!

**Review by benironside — APPROVED** [review]
👍 👍

**Pull request merged**
