### PR TITLE
[DOCS] Update configure-integration-policy.asciidoc

### PR DESCRIPTION
**Pull request by predogma**
It is unclear that Notify User pushes notification to host OS's notification system.  To make it clear suggest adding the tip

TIP: **Notify User** option pushes a notification to the host OS's notification system.

Otherwise it is confusing and expectation might be to look at kibana alert notifcations from a rule or something different then host OS notification

Preview: [Configure an integration policy for Elastic Defend | Malware protection](https://security-docs_3141.docs-preview.app.elstc.co/guide/en/security/current/configure-endpoint-integration-policy.html#malware-protection)

### CODE REVIEW

**Comment by jmikell821** [comment]
@predogma we'll take over the PR from here and will likely add it as a `NOTE:` instead of a tip. Thanks! cc: @joepeeples.

**Comment by joepeeples** [comment]
Note to self: good example for forward-port to `main` (and maybe other backports too).

**Comment by joepeeples** [comment]
This issue actually affects the other protections features also (ransomware, memory threat, and malicious behavior), and it goes back as far as the "Notify user" option existed (starting in [7.11](https://www.elastic.co/guide/en/security/7.11/install-endpoint.html#malware-protection) for malware protection).

I pushed [some changes](https://github.com/elastic/security-docs/pull/3141/commits/e959cef5cbbec39c8350354fb504d7e70a347789) that will update the docs in `8.7`, which we can then forward-port to `main`. Additional backporting to be decided.

**Comment by joepeeples** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|main|[](https://github.com/elastic/security-docs/pull/3163)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
