### PR TITLE
[BUG] Adding .internal indices permission necessity for rule preview feature permission docs

### PR DESCRIPTION
**Pull request by nastasha-solomon**
Fixes https://github.com/elastic/security-docs/issues/3066.

Previews:
- [Enable and access detections](https://security-docs_3067.docs-preview.app.elstc.co/guide/en/security/master/detections-permissions-section.html#enable-detections-ui) - Updated privs for previewing rules
- [Preview your rule (optional)](https://security-docs_3067.docs-preview.app.elstc.co/guide/en/security/master/rules-ui-create.html#preview-rules) - Updated privs mentioned in note.

### CODE REVIEW

**Comment by nastasha-solomon** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by nastasha-solomon** [comment]
@elasticmachine run elasticsearch-ci/docs

**Review by dplumlee — APPROVED** [review]
lgtm

**Review by joepeeples — APPROVED** [review]
LGTM!

**Review by jmikell821 — APPROVED** [review]
LGTM! 👍

**Pull request merged**
