### PR TITLE
[BUGS] Fix 8.7 bugs, screenshots

### PR DESCRIPTION
**Pull request by joepeeples**
Resolves these bugs:

- #3134 
- #3128 
- #3130

Previews:
- https://security-docs_3152.docs-preview.app.elstc.co/guide/en/security/master/rules-ui-create.html#rule-ui-advanced-params
- https://security-docs_3152.docs-preview.app.elstc.co/guide/en/security/master/rules-ui-create.html#create-rule-ui
- https://security-docs_3152.docs-preview.app.elstc.co/guide/en/security/master/response-actions.html#help-panel

### CODE REVIEW

**Review by nastasha-solomon — APPROVED** [review]
lgtm 😄

**Comment by muskangulati-qasource** [comment]
Hi @joepeeples,

We are marking this PR as QA Approved since the [related issue](https://github.com/elastic/security-docs/issues/3130) is validated and closed.

Thanks!

**Review by sukhwindersingh-qasource — APPROVED** [review]
Hi @joepeeples,

We are marking this PR as QA Approved since the related issues is validated and closed.

- https://github.com/elastic/security-docs/issues/3128
- https://github.com/elastic/security-docs/issues/3134

Thanks!

**Comment by joepeeples** [comment]
@elasticmachine run elasticsearch-ci/docs

**Pull request merged**
