### PR TITLE
[DE Team][BUG]: Missing info in req docs for detections 

### PR DESCRIPTION
**Pull request by nastasha-solomon**
Fixes https://github.com/elastic/security-docs/issues/5343

ESS Previews:
- [Detections prerequisites and requirements | Enable and access detections](https://security-docs_bk_5708.docs-preview.app.elstc.co/guide/en/security/master/detections-permissions-section.html#enable-detections-ui): Made several changes:
   - Updated the intro to show that users also need **Data View Management** feature visibility for the Space that they’re working in.  
   - Updated the note in the second row of the table. It now tells users that they need to visit the  **Detection rules (SIEM)** and **Alerts** pages for each appropriate Kibana space to enable the Detections feature for that space. This formerly said to visit the **Detection** pages. 
- [Data views in Elastic Security | The default data view](https://security-docs_bk_5708.docs-preview.app.elstc.co/guide/en/security/master/data-views-in-sec.html#default-data-view-security): Added a note telling users that their Kibana space must have **Data View Management** feature visibility setting enabled for the default data view to generate and become active in your space.

Serverless previews:
- [Explore your data | Data views in Elastic Security | The default data view](https://elastic-dot-co-docs-production-phl73qtp7-elastic-dev.vercel.app/current/serverless/security/data-views-in-sec#the-default-data-source)

### CODE REVIEW

**Comment by nastasha-solomon** [comment]
run docs-build

**Review by joepeeples — DISMISSED** [review]
LGTM, but we might also want to update the corresponding serverless content at the same time. 

Spaces will be supported in serverless GA, and they're already currently [available in QA environments](https://elastic.slack.com/archives/C04ML7QEF5L/p1723649259330829) (3rd bullet). Even if spaces aren't in Prod _quite yet_, it probably wouldn't hurt to include this content a little early, and it'd save future headaches trying to remember what to add back in once spaces do finally drop in Prod.

This is a little tricky since we don't have a "Detections prerequisites and requirements" page in serverless, but maybe this is a good reason to add it back in. We do have a serverless data views page, so at least that could be updated easily now, and maybe spin off a separate issue to handle the Detections stuff later.

**Review by e40pud — DISMISSED** [review]

**Comment by nastasha-solomon** [comment]
Thanks for the review and suggestions @joepeeples. https://github.com/elastic/security-docs/pull/5708/commits/9c6fbd234d8f7e9b2d35fcf240f6dcd212797447 updates the Serverless data view docs, and [this issue](https://github.com/elastic/security-docs/issues/5301) tracks the task of re-adding the priv docs for detection features in Serverless. I'll open a separate PR for 5301 once we start that effort.

**Review by joepeeples — APPROVED** [review]

**Comment by elasticdocs** [comment]
:rocket: Built _elastic-dot-co-docs-preview-docs_ successfully!

* https://elastic-dot-co-docs-production-phl73qtp7-elastic-dev.vercel.app

* Built with commit a5180c03f218e0ce100f0c72b51be7d5d97239ce

> Issues? Visit #next-docs in Slack

**Pull request merged**
