### PR TITLE
Auto-generate preview links for PRs

### LINKED ISSUE #2312: Auto-generate preview links for PRs
## Description 

We can implement a [GitHub Action](https://docs.github.com/en/actions) to automatically generate preview links for our PRs. Several other docs teams/repos already do this, so we can use their solutions as inspiration:

- Enterprise Search - [PR to add action](https://github.com/elastic/enterprise-search-pubs/pull/2666)
- Logstash - [action YAML](https://github.com/elastic/logstash/blob/main/.github/workflows/add-docs-preview-link.yml)

## Acceptance Test Criteria

Preview links are generated when a PR is created, and updated when PR has new changes merged in.

## Notes

- This isn't exactly version-specific, but added `v8.5.0` label as a general window when we want to roll this out (definitely wait until after 8.4.0 release).
- Auto-generated links will probably just be a top-level link to the main landing page, so there will still be value in manually adding links to target only the changed pages. Investigate if we could add any magic to generate targeted links? ✨

## Additional tasks

Reopened this issue to complete a few more tasks, now that we know the action works:

- [x] Backport to rest of 8.x series and 7.17 (use backport tool)
- [x] Update [readme](https://github.com/elastic/security-docs#readme) in `security-docs` to explain how auto-previews work (and backport that too: create new PR and label accordingly so Mergify creates backports)

### PR DESCRIPTION
**Pull request by joepeeples**
Resolves #2312. Adds a GitHub Action that will automatically create preview links when a pull request is created. Links are added in a comment on the PR.

<p align="center">image</p>

## Notes

- The GitHub Action runs as a check alongside other checks (such as CI, Mergify, etc.) but only runs when the PR is first opened.
- Heavily modeled after the GH Action that Enterprise Search recently implemented in https://github.com/elastic/enterprise-search-pubs/pull/2666.
- Future enhancement possibilities: 
    - Wait until CI has successfully built the preview, to ensure no dead links ([Logstash's preview Action](https://github.com/elastic/logstash/blob/main/.github/workflows/add-docs-preview-link.yml) currently does this).
    - Create targeted links to the specific pages changed in the PR (currently the docs link is just top-level landing page).

### CODE REVIEW

**Review by bmorelli25 — APPROVED** [review]
Looks pretty good to me 🚀

**Comment by joepeeples** [comment]
Some teams are using [path filters](https://github.com/elastic/elasticsearch/pull/89670#issuecomment-1228802274) to create preview links only when PRs involving certain paths (such as `docs/*`) or file types (such as `.asciidoc`), but that doesn't seem necessary for the `security-docs` repo.

This repo is self-contained to focus only on docs, so we don't need to account for non-docs PRs the way other teams might if their docs cohabitate with code in the same repo. We can always add filters later if we find the Action to be too noisy, but I think we'll want preview links for the vast majority of PRs in `security-docs`.

**Review by jmikell821 — APPROVED** [review]
This LGTM! 👍 Thanks for getting this set up :)

**Review by nastasha-solomon — APPROVED** [review]
🚀 🚀 🚀

**Comment by joepeeples** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.3|[](https://github.com/elastic/security-docs/pull/2423)|
|✅|8.2|[](https://github.com/elastic/security-docs/pull/2424)|
|✅|8.1|[](https://github.com/elastic/security-docs/pull/2425)|
|✅|8.0|[](https://github.com/elastic/security-docs/pull/2426)|
|✅|7.17|[](https://github.com/elastic/security-docs/pull/2427)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
