### PR TITLE
Generate docs for prebuilt-rules 7.11 release

### LINKED ISSUE #433: [DOCS] Prebuilt rules for 7.11
Placeholder to ensure prebuilt rules and the changelog are added for 7.11. @devonakerr let's sync whenever these are ready so @DonNateR and I can do a QA check to ensure everything looks good.

### PR DESCRIPTION
**Pull request by brokensound77**
Resolves #433 

# Summary

Generated documentation for 7.11 prebuilt rules.

The only thing I was not completely sure of was (I had not generated these docs before): 

>After creating the documentation, you need to copy and paste the files in the generated-ascii-files folder to their relevant location in the docs folder, and then manually edit the text of new rules added for the latest release. This includes converting Markdown to AsciiDoc and editing the English.

I figured once the preview page was generated, any obvious misses would stand out better

### Script changes
I also added a consolidated script to simplify the process and eliminate the need for code changes. 

I didn't do a complete refactor, because I think it will actually make sense to eventually generate these docs within the detection-rules repo directly as part of the package generation process, along with the other artifacts that are generated.

I did a diff using the existing scripts to ensure nothing was incorrectly modified

### CODE REVIEW

**Comment by jmikell821** [comment]
[Rules table preview](https://security-docs_477.docs-preview.app.elstc.co/guide/en/security/master/prebuilt-rules.html)

**Comment by bm11100** [comment]
I took a quick look and it appears like the Google Workspace rules are getting split incorrectly. It occurs for all 10 Workspace rules, splitting at the `note` field.
image

**Comment by brokensound77** [comment]
> I took a quick look and it appears like the Google Workspace rules are getting split incorrectly. It occurs for all 10 Workspace rules, splitting at the `note` field.

Great catch @bm11100, as you mentioned, it looks like it is the markdown causing the issues.

@jmikell821 @DonNateR, should the `Investigation Guide` get wrapped in a `[source,markdown]` block to prevent any further broken renderings, since the `note` field it builds from is markdown? This has not been done in any rule docs to this point, but maybe we have gotten lucky (or it was manually edited). Unless there is a better way (I am not very familiar with asciidoc format)

**Comment by jmikell821** [comment]
Hi @brokensound77 the problem was that the para after `Investigation Guide` was a Level 3 heading (see photo) because of the `###` syntax. Level 3's in our docs get added to the TOC sidebar. I changed the `###` to bold instead `**` it looks better in the preview. @DonNateR is fixing the other 9 files. 
image

**Comment by brokensound77** [comment]
Thanks @jmikell821, that is what I figured as well. 

The only problem with modifying the text (`###`) within the `Investigation Guide` is that it exists like that in the rule itself: https://github.com/elastic/detection-rules/blob/d0ceb8cc4e6b2ea3d127228f9ac5589e71bc8ce6/rules/google-workspace/domain_added_to_google_workspace_trusted_domains.toml#L24-L31

The `note` field which it is built from allows full markdown, so even if we manually modified it, it potentially could occur multiple times. Rather than manually replacing all conflicts between markdown and asciidoc, I figured it would be easier to just escape the whole block of text for the investigation guide, which also makes it more future-proof

**Comment by brokensound77** [comment]
Sorry for all the confusion @jmikell821, but I realized that there was a note that mentioned modifying the markdown as you suggested is what has been all along. So to remain consistent, I went ahead and just updated the files with your recommendation

**Comment by jmikell821** [comment]
> Sorry for all the confusion @jmikell821, but I realized that there was a note that mentioned modifying the markdown as you suggested is what has been all along. So to remain consistent, I went ahead and just updated the files with your recommendation

Thanks @brokensound77 this looks better in my opinion. I'll wait for a few more reviews to look over these before we merge this PR.

**Review by bm11100 — APPROVED** [review]
Looks good to me now, thanks all! 🚢

**Comment by brokensound77** [comment]
Hey @jmikell821 I see you are still awaiting approvals. I just pinged I&A for another review and it sounded like you were going to ask @DonNateR as well. Just didn't want this to slip through the cracks

**Comment by jmikell821** [comment]
> Hey @jmikell821 I see you are still awaiting approvals. I just pinged I&A for another review and it sounded like you were going to ask @DonNateR as well. Just didn't want this to slip through the cracks

Hey @brokensound77 I haven't forgotten! I'll wait for any more reviews today and will merge this in tomorrow. Thanks.

**Review by devonakerr — APPROVED** [review]
Ascii-tastic

**Pull request merged**
