### PR TITLE
Documents reputation service

### LINKED ISSUE #3810: Reputation Service option added to Malicious Behavior Policy card
## Description 

- PR: https://github.com/elastic/kibana/pull/161617
- Issue: https://github.com/elastic/security-team/issues/7051

> Add an option for cloud lookup to the Malicious Behavior Policy card. This option enables/disables the Reputation Service feature in Endpoint. When the option is ON, Endpoint will reach out to a Cloud API for additional malware analysis. When it's OFF, Endpoint will not reach out to the Cloud API.
> 
> test

### PR DESCRIPTION
**Pull request by natasha-moore-elastic**
- Resolves #3810 

Preview: [Configure an integration policy for Elastic Defend | Malicious behavior protection](https://security-docs_3855.docs-preview.app.elstc.co/guide/en/security/master/configure-endpoint-integration-policy.html#behavior-protection)

### CODE REVIEW

**Comment by szwarckonrad** [comment]
I believe it might be worth highlighting that only cloud users will see this option; for any other installation type, this option simply won't be there :). The sentence `Select whether you want to use Reputation service for additional malware analysis. This is a cloud service that can identify malicious activity and false positives...` makes it sound like the service itself is cloud-based, rather than indicating the availability of the feature. What do you think?

**Comment by natasha-moore-elastic** [comment]
> I believe it might be worth highlighting that only cloud users will see this option; for any other installation type, this option simply won't be there :). The sentence `Select whether you want to use Reputation service for additional malware analysis. This is a cloud service that can identify malicious activity and false positives...` makes it sound like the service itself is cloud-based, rather than indicating the availability of the feature. What do you think?

That makes sense, thanks @szwarckonrad! How does this sound: 

`Select whether you want to use Reputation service for additional malware analysis. This service identifes malicious activity and false positives, and enriches alerts using data from various sources...`

...

` NOTE: Reputation service is available to Elastic Cloud users only and requires an active Platinum or Enterprise subscription.`

**Comment by szwarckonrad** [comment]
Sounds good to me!

**Comment by szwarckonrad** [comment]
@kevinlog 
Could you have a look?

**Review by kevinlog — APPROVED** [review]
thanks for the ping @szwarckonrad - this looks good to me.  I think @roxana-gheorghe should but the main approver of how the feature is described to users.

**Comment by roxana-gheorghe** [comment]
I think we should avoid the confusion between Elastic Cloud and Cloud Security, the current offering on our website.
Can we say something like:

 NOTE: Reputation service  requires an active Platinum or Enterprise subscription and is available to Cloud users only.

or

 NOTE: Reputation service  requires an active Platinum or Enterprise subscription and is not available to Self-managed users.

**Comment by natasha-moore-elastic** [comment]
> I think we should avoid the confusion between Elastic Cloud and Cloud Security, the current offering on our website. Can we say something like:
> 
> NOTE: Reputation service requires an active Platinum or Enterprise subscription and is available to Cloud users only.
> 
> or
> 
> NOTE: Reputation service requires an active Platinum or Enterprise subscription and is not available to Self-managed users.

Thanks for this @roxana-gheorghe!
@elastic/security-docs, could you let me know how we would typically refer to this in the docs?

**Comment by natasha-moore-elastic** [comment]
> I think we should avoid the confusion between Elastic Cloud and Cloud Security, the current offering on our website. Can we say something like:
> 
> NOTE: Reputation service requires an active Platinum or Enterprise subscription and is available to Cloud users only.
> 
> or
> 
> NOTE: Reputation service requires an active Platinum or Enterprise subscription and is not available to Self-managed users.

Hey @roxana-gheorghe, I've modified the note slightly to hopefully make this clearer:
`NOTE: Reputation service requires an active Platinum or Enterprise subscription and is available on cloud deployments only.`
Let me know if that sound good to you.

**Review by benironside — APPROVED** [review]
LGTM

**Pull request merged**
