### PR TITLE
SentinelOne bidirectional `processes`, `kill-process`, and detection rule updates  [serverless]

### PR DESCRIPTION
**Pull request by joepeeples**
This PR bundles several updates to the SentinelOne bidirectional integration features for **_serverless only_** (ESS updates in a separate PR TBD):
- https://github.com/elastic/security-docs/issues/5638
- https://github.com/elastic/security-docs/issues/5590
- https://github.com/elastic/security-docs/issues/5637

> [!NOTE]
> The PR's branch was created as a sub-branch of the branch `5446-crowdstrike-response-actions`, used in the PR https://github.com/elastic/security-docs/pull/5529. I needed to build off the restructuring done in that PR, which hasn't been merged yet but probably will be before it's time to merge the current PR. I'm trying out this technique as an experiment and it's working out so far, but really hoping it doesn't bite me later.  🙀 

### Previews

Click the [link below](https://github.com/elastic/security-docs/pull/5659#issuecomment-2266015167), then in the Security card click **View serverless docs**. Navigate to these pages:
- **Endpoint response actions** — Revised sections for `processes` and `kill-process` to reference S1 differences.
- **Endpoint response actions | Third-party response actions** — Added bullets to the SentinelOne tab.
- **Endpoint response actions | Configure third-party response actions** | **SentinelOne** tab — Revised final step about creating detection rules.

### CODE REVIEW

**Comment by elasticdocs** [comment]
:rocket: Built _elastic-dot-co-docs-preview-docs_ successfully!

* https://elastic-dot-co-docs-production-a4r7jjw02-elastic-dev.vercel.app

* Built with commit e8c83be2ad9f74eeeb15d2f4231aa3956a7efef1

> Issues? Visit #next-docs in Slack

**Review by paul-tavares — APPROVED** [review]
Looks good @joepeeples - thank you.

FYI: I'm not able to find the changes in the doc preview link. Not sure if they got generated correctly

**Comment by joepeeples** [comment]
> FYI: I'm not able to find the changes in the doc preview link. Not sure if they got generated correctly

Yeah, links generated by Vercel are not super reliable. The URL changes every time a commit happens, so this is the main response actions page (with updates in the subsections on `processes` and `kill-process`) but is subject to change if I make any further changes:

https://elastic-dot-co-docs-production-gk8a67h2b-elastic-dev.vercel.app/current/serverless/security/response-actions

From there you can use the side TOC to navigate to other third-party response actions pages.

**Comment by paul-tavares** [comment]
Thanks @joepeeples . I just access them with the link you provided and looks good 👍

**Review by nastasha-solomon — APPROVED** [review]

**Review by benironside — APPROVED** [review]
LGTM

**Pull request merged**
