### PR TITLE
[DOCS] Download prebuilt rules (7.13 addendum)

### PR DESCRIPTION
**Pull request by jmikell821**
Addresses [this comment](https://github.com/elastic/security-team/issues/17#issuecomment-856324687). 
Related: #720 

Preview [here](https://security-docs_777.docs-preview.app.elstc.co/guide/en/security/master/rules-ui-management.html#rules-ui-management).

### CODE REVIEW

**Comment by jmikell821** [comment]
Hi @rw-access - please review this PR (preview link is in the first comment) and let me know if I need to make any further adjustments. I understand that for 7.14, we'll have to revise slightly since Integrations is moving to its own section in the new navigation.

**Review by rw-access — APPROVED** [review]
this looks great, thanks @jmikell821! will this change be made to the 7.13 docs or 7.14 docs?

for some reason the pictures render a little fuzzy for me, but look fine when I open in a new tab.

**Review by nastasha-solomon — APPROVED** [review]
LGTM!

**Comment by jmikell821** [comment]
> this looks great, thanks @jmikell821! will this change be made to the 7.13 docs or 7.14 docs?
> 
> for some reason the pictures render a little fuzzy for me, but look fine when I open in a new tab.

Hey @rw-access, if the images look like this on your end, that's how the resolution renders unfortunately with our docs. We're hoping images will be a bit clearer when we launch the new docs system. These changes will be backported to 7.13 and 7.x, so it'll appear in 7.14 as well.

**Pull request merged**
