### PR TITLE
[BUG][ESS] Elastic AI Assistant feature missing in Kibana Privilege

### PR DESCRIPTION
**Pull request by nastasha-solomon**
Fixes https://github.com/elastic/security-docs/issues/4627

[Preview](https://security-docs_bk_4659.docs-preview.app.elstc.co/guide/en/security/master/case-permissions.html) - updated screenshot

### CODE REVIEW

**Comment by nastasha-solomon** [comment]
run docs-build

**Comment by karanbirsingh-qasource** [comment]
@nastasha-solomon looks like preview link is not being yet added in comment or generated.

we have tried this link but too is showing 404 .

https://buildkite.com/elastic/docs-build-pr/builds/17165

**Review by joepeeples — DISMISSED** [review]

**Comment by nastasha-solomon** [comment]
@karanbirsingh-qasource sorry about that. I've generated the HTML preview locally and here's a screenshot of the page:

Screenshot 2024-01-24 at 9 50 19 AM


Does this help? If not, I can try one more thing so the preview generates for this PR.

**Comment by nastasha-solomon** [comment]
@elasticsearchmachine run docs-build rebuild

**Review by joepeeples — APPROVED** [review]

**Comment by nastasha-solomon** [comment]
@karanbirsingh-qasource sorry about that. It should be fixed now.

**Pull request merged**
