### PR TITLE
[DOCS] Advanced Settings: CCS privileges warning

### LINKED ISSUE #1820: [DOCS] Advanced Settings: CCS privileges warning
## Description 

Adds an advanced setting toggle to optionally disable cross cluster search read privilege warnings on rule execution. Default behavior is set to true and is how it the code currently functions. With it disabled, the cross cluster search indices are filtered out when logging any read privilege warnings. 

Screen Shot 2022-02-02 at 2 45 09 PM

Related:
* PR: https://github.com/elastic/kibana/pull/124459

### PR DESCRIPTION
**Pull request by joepeeples**
Resolves #1820.

Preview: [Configure advanced settings | Configure cross-cluster search privilege warnings](https://security-docs_1829.docs-preview.app.elstc.co/guide/en/security/master/advanced-settings.html#enable-ccs-warning)

### CODE REVIEW

**Review by dplumlee — APPROVED** [review]
The CCS advanced setting stuff looks great thanks!

**Review by benironside — APPROVED** [review]
LGTM

**Review by nastasha-solomon — APPROVED** [review]
LGTM!

**Review by jmikell821 — APPROVED** [review]
LGTM!

**Review by marshallmain — APPROVED** [review]

**Review by jethr0null — APPROVED** [review]
Looks good from the product perspective

**Comment by prachigupta-qasource** [comment]
Hi @joepeeples ,

We tested the linked docs and found that all the docs are correctly updated as per the latest UI. So we are good to go ahead and merge the changes.

Marking this ticket as 'QA validated'.

Thanks!

**Pull request merged**
