### PR TITLE
[BUG] Users page bug fixes for 8.2

### PR DESCRIPTION
**Pull request by joepeeples**
Resolves:
- https://github.com/elastic/security-docs/issues/1946
- https://github.com/elastic/security-docs/issues/1952

Preview: [Elastic Security UI | Page navigation](https://security-docs_1966.docs-preview.app.elstc.co/guide/en/security/master/es-ui-overview.html#page-tabs)

### CODE REVIEW

**Review by benironside — APPROVED** [review]
LGTM!

**Review by nastasha-solomon — APPROVED** [review]
LGTM, thanks!

**Review by karanbirsingh-qasource — APPROVED** [review]
Approved !!

**Review by jmikell821 — APPROVED** [review]
LGTM - somehow the side nav gif I updated didn't get saved in my PR, so thanks for adding it here!

**Pull request merged**
