### PR TITLE
[DOCS] Add note that binary fields are not supported in detection rule exceptions

### LINKED ISSUE #1681: [DOCS] Add note that `binary` fields are not supported in Detection Rule Exceptions
## Description 

A recent issue was identified (https://github.com/elastic/kibana/issues/127168) where using fields of type `binary` within Rule Exceptions would result in the rule failing execution. Currently the UI allows selection of these field types, so users can end up with failing rules and no clear remediation steps. This issue is for either adding a note to the [exceptions docs](https://www.elastic.co/guide/en/security/current/detections-ui-exceptions.html#detections-ui-exceptions) or listing https://github.com/elastic/kibana/issues/127168 as a known issue, whichever you think makes the most sense from a docs perspective.

## Acceptance Test Criteria

As a user, I should be able to identify un/supported field types that can be used within exceptions, and/or any known issues around their use.

## Notes

This issue was discovered in `8.2`/`main`, and is present in all versions of the stack that have shipped with exceptions `7.9+`.

### PR DESCRIPTION
**Pull request by joepeeples**
Resolves #1681. 

Documented as a note within the exception docs (vs. a "known issue" in release notes) since this spans many versions. Also backporting to 8.0.0, but can go further back if necessary.

Preview: [Rule exceptions and value lists](https://security-docs_1977.docs-preview.app.elstc.co/guide/en/security/master/detections-ui-exceptions.html)

### CODE REVIEW

**Review by nastasha-solomon — APPROVED** [review]

**Review by jmikell821 — APPROVED** [review]
LGTM!

**Review by spong — APPROVED** [review]
LGTM -- thanks @joepeeples! 🙂

**Review by benironside — APPROVED** [review]
LGTM!

**Review by jmikell821 — APPROVED** [review]

**Comment by joepeeples** [comment]
@elasticmachine run elasticsearch-ci/docs

**Review by jethr0null — APPROVED** [review]
LGTM

**Pull request merged**
