### PR TITLE
[815][ESS] Gen AI updates

### PR DESCRIPTION
**Pull request by benironside**
Twin PR of #5668. Assorted minor updates to generative AI docs.

Preview: [AI Assistant](https://security-docs_bk_5673.docs-preview.app.elstc.co/guide/en/security/master/security-assistant.html)

### CODE REVIEW

**Comment by benironside** [comment]
run docs-build

**Comment by joepeeples** [comment]
I just reviewed https://github.com/elastic/security-docs/pull/5668 with a few suggestions, so let me know when you've applied changes to this PR and I can do a quick review & approve here too!

**Review by joepeeples — APPROVED** [review]
LGTM!

**Review by joepeeples — APPROVED** [review]
👍

**Pull request merged**
