### PR TITLE
[BUG] Incorrect Type of value list name are displayed in value list 

### PR DESCRIPTION
**Pull request by nastasha-solomon**
Addresses #737. 

Preview [here](https://security-docs_880.docs-preview.app.elstc.co/guide/en/security/master/detections-ui-exceptions.html).

### CODE REVIEW

**Review by joepeeples — APPROVED** [review]
LGTM!

**Comment by jmikell821** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by deepikakeshav-qasource** [comment]
Hi @nastasha-solomon ,

Required changes are now present in the shared guide.

image

Hence, approving the PR request.

Thanks!!

**Review by deepikakeshav-qasource — APPROVED** [review]
Approved!!

**Review by jmikell821 — APPROVED** [review]
LGTM!

**Pull request merged**
