### PR TITLE
[BUG] Refreshing outdated images and gifs that demonstrate UI accessibility options and how to investigate IoCs in Timeline

### PR DESCRIPTION
**Pull request by nastasha-solomon**
Fixes https://github.com/elastic/security-docs/issues/5692

Previews:
- **ESS:** 
   - [Elastic Security UI | Accessibility features](https://security-docs_bk_5700.docs-preview.app.elstc.co/guide/en/security/master/es-ui-overview.html#timeline-accessibility-features)
   - [Indicators of compromise | Find related security events](https://security-docs_bk_5700.docs-preview.app.elstc.co/guide/en/security/master/indicators-of-compromise.html#find-related-sec-events) 
- **Serverless:** 
   - [Elastic Security UI | Accessibility features](https://elastic-dot-co-docs-production-5iqg4le2x-elastic-dev.vercel.app/current/serverless/security/security-ui#accessibility-features)
   - [Indicators of compromise | Find related security events](https://elastic-dot-co-docs-production-5iqg4le2x-elastic-dev.vercel.app/current/serverless/security/indicators-of-compromise#find-related-security-events)

### CODE REVIEW

**Comment by elasticdocs** [comment]
:rocket: Built _elastic-dot-co-docs-preview-docs_ successfully!

* https://elastic-dot-co-docs-production-32ifa7ncf-elastic-dev.vercel.app

* Built with commit 0c2d9567e6000b2b686ac6ec4cb19d3a457b4951

> Issues? Visit #next-docs in Slack

**Review by joepeeples — APPROVED** [review]
So many images! LGTM, but would love to take a hard look at reducing the maintenance burden sometime.

**Comment by nastasha-solomon** [comment]
> So many images! LGTM, but would love to take a hard look at reducing the maintenance burden sometime.

@joepeeples hard agree. I think the visuals complement the explanations well, but I also think the explanations are descriptive enough to stand on their own. I don't think we'd lose any clarity if we decided to remove some of the similar gifs (e.g., showing how to navigate the UI using the `Tab` button) or all of them in the "Accessibility features" section.

**Comment by joepeeples** [comment]
> I don't think we'd lose any clarity if we decided to remove some of the similar gifs (e.g., showing how to navigate the UI using the Tab button) or all of them in the "Accessibility features" section.

Yeah, no need to remove anything right now, since you've already done the work to update them. But we could spin off a separate housekeeping issue to reconsider keeping them for future.

**Comment by nastasha-solomon** [comment]
Merging this PR for now so the docs are updated. @logeekal and @michaelolo24 I'll open a separate doc issue and PR if we need release-note known UI bugs.

**Pull request merged**
