### PR TITLE
CSPM onboarding updates

### LINKED ISSUE #3989: CSPM Onboarding updates
Post-8.10 release, review by product of the CSPM onboarding docs came up with some feedback / improvements, which can be reviewed here: https://github.com/elastic/security-team/issues/7657.
 
Should be approved by Tinsae

### PR DESCRIPTION
**Pull request by benironside**
Fixes #3989, which identified a couple of recommendations for additional info to include in docs that we got from product after the 8.10 release.

Previews: 
[CSPM AWS onboarding](https://security-docs_3990.docs-preview.app.elstc.co/guide/en/security/master/cspm-get-started.html)
[CSPM GCP onboarding](https://security-docs_3990.docs-preview.app.elstc.co/guide/en/security/master/cspm-get-started-gcp.html)

### CODE REVIEW

**Review by joepeeples — COMMENTED** [review]
Added a couple of edits, thanks!

Also, unrelated to this particular update, but this is a good time to start making sure the serverless docs get the same updates as the classic docs. Basically open a PR in [staging-serverless-security-docs](https://github.com/elastic/staging-serverless-security-docs) that applies the same updates to these pages in serverless docs:

* [Get started with CSPM for AWS](https://github.com/elastic/staging-serverless-security-docs/blob/main/docs/cloud-native-security/cspm-get-started.mdx)
* [Get started with CSPM for GCP](https://github.com/elastic/staging-serverless-security-docs/blob/main/docs/cloud-native-security/cspm-get-started-gcp.mdx)

**Review by orestisfl — APPROVED** [review]
AWS changes look good

**Review by uri-weisman — APPROVED** [review]

**Review by nastasha-solomon — APPROVED** [review]
LGTM!

**Review by tinnytintin10 — COMMENTED** [review]
@benironside I noticed the manual instructions for AWS org onboarding are not in the side navigation. It's also found outside of the manual instructions section. Was this intentional? 

Screenshot 2023-09-27 at 17 13 38

**Pull request merged**
