### PR TITLE
add docs for 7.11.2 pre-built rules

### LINKED ISSUE #580: [DOCS] Prebuilt rules for 7.11.2
## Description 

Generate docs for 7.11.2 prebuilt rule changes

## Acceptance Test Criteria

List all the ATC of each action and its intended result. 
As a user, when [action (e.g., viewing, clicking, selecting, etc.)] the [insert the expected result]. 
If the doc issue includes a procedure, number the steps in sequential order.  

## Notes

- Add the **"Team:Docs"** label to new issues. 
- Be sure to add the version number label. 
- Be sure to add any necessary screenshots for clarity. 
- Include any conditions or caveats that may affect customers.

### PR DESCRIPTION
**Pull request by brokensound77**
resolves #580

Add docs for prebuilt rule changes for 7.11.2

[Preview link](https://security-docs_581.docs-preview.app.elstc.co/guide/en/security/7.11/prebuilt-rules.html).

### CODE REVIEW

**Comment by jmikell821** [comment]
Hey @brokensound77 I didn't see any rules for 7.11.2 when I ran a search -- just wanted to confirm that was the behavior as expected.

**Review by bm11100 — APPROVED** [review]
versions look good to me

**Comment by brokensound77** [comment]
> Hey @brokensound77 I didn't see any rules for 7.11.2 when I ran a search -- just wanted to confirm that was the behavior as expected.

Yep that is accurate - ARAIR we didn't add new rules to 7.11.2, so as of _this_ update, the newest are from 7.1..0

**Review by jmikell821 — APPROVED** [review]
LGTM!

**Pull request merged**
