### PR TITLE
[DOCS] Resolving additional QA-reported doc bugs

### PR DESCRIPTION
**Pull request by nastasha-solomon**
1. Addresses #619 [here](https://security-docs_643.docs-preview.app.elstc.co/guide/en/security/master/visual-event-analyzer.html).   
2. Addresses #614 [here](https://security-docs_643.docs-preview.app.elstc.co/guide/en/security/master/admin-page-ov.html). 
3. Addresses #631 [here](https://security-docs_643.docs-preview.app.elstc.co/guide/en/security/master/install-endpoint.html#register-as-antivirus). 
4. Additional changes related to #621 [here](https://security-docs_643.docs-preview.app.elstc.co/guide/en/security/master/cases-ui-integrations.html) and [here](https://security-docs_643.docs-preview.app.elstc.co/guide/en/security/master/cases-overview.html). Need the list of available connectors (list is located at the start of the topic) and step 3 in the procedure that follows reviewed please!
5. Addresses #613 here.

### CODE REVIEW

**Comment by muskangulati-qasource** [comment]
Hi @nastasha-solomon,

The link added for issue #614 is not correct. Can you please share the link for the correct page?

We will review the PR !

Thanks!!

**Comment by nastasha-solomon** [comment]
@muskangulati-qasource apologies and link fixed for #614. :)

**Comment by muskangulati-qasource** [comment]
Hi @nastasha-solomon,

Only **01** ticket is left for changes: https://github.com/elastic/security-docs/issues/621

Once, done this PR is good to be merged.

Thanks!

**Review by muskangulati-qasource — APPROVED** [review]
Approved!! As all the related bugs are fixed!

**Pull request merged**
