### PR TITLE
[Detection Rules] Adding Documents for v8.13.3 Pre-Built Detection Rules

### PR DESCRIPTION
**Pull request by protectionsmachine**
Security Doc updates for prebuilt security rule integration package version v8.13.3. Please note these are meant to merge into 8.13 only and not backport.

### CODE REVIEW

**Comment by eric-forte-elastic** [comment]
Just checking would we expect 8.13.3 to be present in the Downloadable Rule Updates?
image

**Comment by eric-forte-elastic** [comment]
Looks like the update is available in preview
image

**Review by eric-forte-elastic — APPROVED** [review]

**Comment by shashank-elastic** [comment]
Yes @eric-forte-elastic its present here 
https://security-docs_bk_5036.docs-preview.app.elstc.co/guide/en/security/current/prebuilt-rules-downloadable-updates.html

image

If your checking from the link pasted on trade slack channel, that was specific example for building docs for 8.10.15. where u will find historical docs plus new docs for 8.10.15. You need to go into each PR build and check the unique staged docs.

**Comment by eric-forte-elastic** [comment]
> Yes @eric-forte-elastic its present here https://security-docs_bk_5036.docs-preview.app.elstc.co/guide/en/security/current/prebuilt-rules-downloadable-updates.html
> 
> image
> 
> If your checking from the link pasted on trade slack channel, that was specific example for building docs for 8.10.15. where u will find historical docs plus new docs for 8.10.15. You need to go into each PR build and check the unique staged docs.

I'm using the correct link :slightly_smiling_face:

**Pull request merged**
