### PR TITLE
Rule exceptions can expire and misc. exception UI changes

### LINKED ISSUE #2891: Rule exceptions can expire
## Description 

In 8.7, users will be able to set an expiration date for regular exceptions. Active and expired exceptions are kept within the exception details and can be viewed from the **Rule exceptions** tab of the rule details page or the details page of a shared exception list. 

After you create the exception, the expiration date and time is provided in the exception details. Active exceptions are displayed by default. To view expired exceptions _in addition_ to active exceptions, click the **Expired exceptions** button. 

Screenshot 2023-03-09 at 2 51 05 PM

### Related issues/PRs
- https://github.com/elastic/security-team/issues/3023
- https://github.com/elastic/kibana/pull/145180

## Doc updates
- [x]  [Add exceptions to a rule](https://www.elastic.co/guide/en/security/master/add-exceptions.html#detection-rule-exceptions): Add an optional step after Step 6 for selecting an expiration date. 
- [x] [Add exception items to shared lists](https://www.elastic.co/guide/en/security/master/shared-exception-lists.html#add-exception-items): Add optional step after Step 7 for selecting expiration date.
- [x] [View and manage exceptions](https://www.elastic.co/guide/en/security/master/add-exceptions.html#manage-exception): Note that users can view active or expired exceptions. Mention default view (is the Active exceptions tab/view) and briefly describe how to display one or both. 
- [x] [Create exception item API docs](https://www.elastic.co/guide/en/security/current/exceptions-api-create-exception-item.html): Add the new `expire_time` parameter. This is an optional parameter that accepts a date in ISO format. The default setting is undefined (the parameter is not included in the request). 
- [x] [Update exception item API docs](https://www.elastic.co/guide/en/security/current/exceptions-api-update-item.html): Add the new `expire_time` parameter.
   - [x] Include note about unsetting optional parameters in this API. Will also release-note it. 
- [x] [Manage shared exception lists](https://www.elastic.co/guide/en/security/master/shared-exception-lists.html#manage-exception-lists): Add a bullet to the list about exporting expired exceptions. Also refresh screenshot. 
- [x] Mandatory screenshot refreshes:
   - [x] `add-exception-ui.png`
   - [x] `rule-exception-tab.png`
   - [x] `exception-affects-multiple-rules.png`
   - [x] `manage-default-rule-list.png`
   - [x] `actions-exception-list.png` (to account for button renaming in https://github.com/elastic/security-docs/issues/3010)
   - [x] `default-rule-list.png`
   - [x] `upload-lists-ui.png` and `manage-value-list.png` (to account for https://github.com/elastic/security-docs/issues/3027)

## Questions

- Q: Is it mandatory for users to set an expiration date?
   - A: Looks like users won't be blocked from creating an exception if they leave the Exception Expiration field blank.  
- Q: Can users bulk apply the same expiration date/time to a set of exception items in a default rule list or shared exception list?
  - A: No 
- Can users set and retrieve expiration date/time details via the exceptions API?
   -A: Yes, they will need to set the `expire_time` parameter. This is an optional field that's can take a date (string) in ISO format.

## Notes
- Changes in https://github.com/elastic/kibana/pull/151952 affect the [Update exception item](https://www.elastic.co/guide/en/security/current/exceptions-api-update-item.html) and [Create exception item](https://www.elastic.co/guide/en/security/current/exceptions-api-create-exception-item.html) APIs. Essentially, if users want to unset an optional field (e.g., the `expire_time` field, they'll need to omit (remove) the field from the request. This should be release-noted as an enhancement. 
- In 8.7, this feature is only available for regular exceptions, _not_ Endpoint exceptions. 
- Times are offered in 30 min increments but users can edit the time directly by making changes to the **Exception Expiration** field. 
Screenshot 2023-03-09 at 4 05 23 PM

- Can view active and expired exceptions from the default rule list.
- When setting an expiration date, the selected date and time must be in the future. 
- Active and expired exceptions are exported/imported with exported/imported rules.  
  - When you export a rule, the active and expired exceptions are included in the export file. Note that there's no notification that you're exporting/importing the deadlines during the import/export process. 
- When you export a shared exception list that has expired exception items, you're prompted to verify that you want to export the expired exceptions. 
Screenshot 2023-03-21 at 1 42 33 PM

- Duplicate rules with active or expired exceptions (the duplicated rule with have both as long as you select the option to duplicate the rule with its exceptions).   
- After you save the exception, it shows up on the **Active exceptions** tab in the Rule exceptions tab/page.
- Notes about the **Active exceptions** and **Expired exception** tabs:
  - Can't toggle between the **Active exceptions** and **Expired exception** tabs. If only want to see one page, will need to click on the tab that you don't want to see to de-select it. 
  - After an exception expires, the expiration date shows `00:00:00.00` but you have to refresh the page for the exception to be moved over to the **Expired exception** tab. It doesn't automatically happen if you're just sitting on the page. 
  
Screenshot 2023-03-09 at 3 04 20 PM

  - The shared exception list details page does not have either tabs. Expiration details are only stored in the exception item details. 

Screenshot 2023-03-09 at 3 23 41 PM

### PR DESCRIPTION
**Pull request by nastasha-solomon**
Fixes #2891, https://github.com/elastic/security-docs/issues/3027, and https://github.com/elastic/security-docs/issues/3010.

Previews:
- [Default rule lists](https://security-docs_3052.docs-preview.app.elstc.co/guide/en/security/master/detections-ui-exceptions.html#default-rule-list-intro): Refreshed screenshot.
- [Create and manage value lists](https://security-docs_3052.docs-preview.app.elstc.co/guide/en/security/master/value-lists-exceptions.html): Refreshed both screenshots and step 6 under [Create value lists](https://security-docs_3052.docs-preview.app.elstc.co/guide/en/security/master/value-lists-exceptions.html#manage-value-lists).
- [Add exceptions to a rule](https://security-docs_3052.docs-preview.app.elstc.co/guide/en/security/master/add-exceptions.html#detection-rule-exceptions): Added step 7 for expiry date and refreshed screenshot after step 2.
- [View and manage exceptions](https://security-docs_3052.docs-preview.app.elstc.co/guide/en/security/master/add-exceptions.html#manage-exception): Mentioned that you can toggle between active or expired exceptions. Also refreshed screenshot.
- [Find rules using the same exceptions](https://security-docs_3052.docs-preview.app.elstc.co/guide/en/security/master/add-exceptions.html#rules-using-same-exception): Refreshed screenshot.
- [Add exception items to shared lists](https://security-docs_3052.docs-preview.app.elstc.co/guide/en/security/master/shared-exception-lists.html#add-exception-items): Added step 8 for expiry date.
- [Associate shared exception lists with rules](https://security-docs_3052.docs-preview.app.elstc.co/guide/en/security/master/shared-exception-lists.html#link-shared-exception-lists): Updated instructions that mentioned the old **Manage rules** button. 
- [Manage shared exception lists](https://security-docs_3052.docs-preview.app.elstc.co/guide/en/security/master/shared-exception-lists.html#manage-exception-lists): Added fourth bullet and refreshed screenshot that showed the old **Manage rules** option. 
- [Create exception item](https://security-docs_3052.docs-preview.app.elstc.co/guide/en/security/master/exceptions-api-create-exception-item.html#_request_body_11): Doc'd the new `expire_time` field.
- [Update exception item](https://security-docs_3052.docs-preview.app.elstc.co/guide/en/security/master/exceptions-api-update-item.html#_request_body_14): Doc'd the new `expire_time` field.

### CODE REVIEW

**Review by dhurley14 — APPROVED** [review]
Looks perfect! Thanks @nastasha-solomon!!

**Review by yctercero — APPROVED** [review]
Looks good - thank you!!

**Review by dplumlee — APPROVED** [review]
Lgtm!

**Review by benironside — APPROVED** [review]
LGTM! Clear text and very thorough image refresh 🚀

**Review by jmikell821 — COMMENTED** [review]
One small nit, then good to go!

**Review by joepeeples — APPROVED** [review]
LGTM!

**Pull request merged**
