### PR TITLE
[DOCS] Changes to message shown in TI card

### PR DESCRIPTION
**Pull request by nastasha-solomon**
Fixes https://github.com/elastic/security-docs/issues/1579.

Previews:
- [Elastic Security UI | Overview | Threat Intelligence](https://security-docs_1809.docs-preview.app.elstc.co/guide/en/security/master/es-ui-overview.html#overview-ui)
- [Enable threat intelligence integrations](https://security-docs_1809.docs-preview.app.elstc.co/guide/en/security/master/es-threat-intel-integrations.html) (In addition to refreshing the screenshot at the start of the topic, I also removed note under step 4 of the [Add an Elastic Agent integration](https://security-docs_1809.docs-preview.app.elstc.co/guide/en/security/master/es-threat-intel-integrations.html#agent-ti-integration) section since it no longer applies.)

### CODE REVIEW

**Review by joepeeples — APPROVED** [review]
LGTM!

**Review by nkhristinin — APPROVED** [review]
LGTM!

**Review by benironside — APPROVED** [review]
LGTM!

**Review by jmikell821 — APPROVED** [review]
LGTM!

**Comment by karanverma-qasource** [comment]
Hi @jmikell821,

We have reported the 03 issues for the docs related to this PR here:


- https://github.com/elastic/security-docs/issues/1878
- https://github.com/elastic/security-docs/issues/1876
- https://github.com/elastic/security-docs/issues/1879

We will validate this PR once the above issues are fixed.

Thanks!

**Comment by karanverma-qasource** [comment]
Hi @jmikell821  ,

We tested the linked docs for the reported bugs and found that all the docs are correctly updated as per the latest UI. So we are good to go ahead and merge the changes.

Marking this ticket as 'QA validated'.

Thanks!

**Pull request merged**
