### PR TITLE
[Docs] Adds 7.10 Cases API updates

### PR DESCRIPTION
**Pull request by cnasikas**
Updates the API docs with the new connectors' fields for 7.10.0.

### CODE REVIEW

**Comment by DonNateR** [comment]
@cnasikas: Looks good other than a few build errors. Mind if I take this over??

**Comment by cnasikas** [comment]
> @cnasikas: Looks good other than a few build errors. Mind if I take this over??

Of course!

**Review by DonNateR — APPROVED** [review]
LGTM.

**Review by DonNateR — APPROVED** [review]
@cnasikas: everything looks good barring a few grammatical changes. I'll take over the PR and merge from here.

**Pull request merged**
