### PR TITLE
[DOCS] Updates to Elastic Security Overview

### PR DESCRIPTION
**Pull request by jmikell821**
Addresses the following: 

- #468 
- #428

### CODE REVIEW

**Comment by jmikell821** [comment]
Hi @ferullo the paragraph on self protection is [here](https://security-docs_476.docs-preview.app.elstc.co/guide/en/security/master/es-overview.html#self-protection). Please review. 

Note: I will make a small grammatical change so this says `"self-protection"` (me nitpicking).

**Comment by kostasb** [comment]
LGTM regarding the Overview / `ECS compliance data requirements` and `c. Indicator index patterns` note, thanks!

**Comment by ferullo** [comment]
I think we should remove everything from `Administrator/root users can stop the Elastic Agent’s service.` and later. Those are details we don't need to document IMHO.

We should also add the Windows and macOS version that support this. Self Protection is enabled on the following 64bit Windows variants: Windows 8.1, Windows 10, Windows Server 2012 R2. Windows Server 2016, Windows Server 2019. For macOS, Self Protection is enabled on macOS 10.15 (Catalina) and macOS 11 (Big Sur).

**Comment by bjmcnic** [comment]
I agree with @ferullo that we should remove everything after `....users can stop the Elastic Agent's service.`. If that's not done though, then the `sc stop "Elastic Endpoint"` is incorrect, it should be `sc stop "Elastic Agent"`.

In the indented note, is the comma following the e.g. (`e.g.,`) intended or a typo?  I haven't seen that before, but I'm not a great writer.

**Comment by jmikell821** [comment]
@ferullo @bjmcnic please glance over the latest [preview](https://security-docs_476.docs-preview.app.elstc.co/guide/en/security/master/es-overview.html#self-protection). 

@bjmcnic in re: to your question about `e.g.,` yes - it basically translates to "for example" so it typically is followed by a comma. But I took this sentence out, per you all's recommendation :)

**Comment by ferullo** [comment]
👍 LGTM

**Comment by bjmcnic** [comment]
LGTM too.

**Pull request merged**
