### PR TITLE
Update suspicious-managed-code-hosting-process.asciidoc

### LINKED ISSUE #4238: Reference Blog is no longer available
## Description 

The reference in https://www.elastic.co/guide/en/security/current/suspicious-managed-code-hosting-process.html is no longer available. 
We can update the reference link to point to the article on the wayback machine here: https://web.archive.org/web/20230329154538/https://blog.menasec.net/2019/07/interesting-difr-traces-of-net-clr.html

## Acceptance Test Criteria

As a user, when visiting the reference links I want them to take me to a live page with the desired content. 
 

## Notes

- Add all appropriate labels to the issue, especially the version number label. 
- Be sure to add any necessary screenshots, code text or console commands for clarity. 
- Include any conditions or caveats that may affect customers.

### PR DESCRIPTION
**Pull request by stiltz**
Update reference link to point to wayback machine as original source is no longer available

This closes #4238

### CODE REVIEW

**Comment by stiltz** [comment]
I'm not able to add reviewers or labels per the guidance in the readme.
FYI @elastic/security-docs

**Comment by jmikell821** [comment]
Hi @stiltz - has the link changed as of `8.11.0` -- or was it previously? Trying to see how far we can backport.

**Comment by stiltz** [comment]
@jmikell821 It looks like all versions of 8.x and starting with 7.10

**Comment by terrancedejesus** [comment]
@Samirbous or @w0rk3r can you chime in on this one.
Last I recall, this was a blog site that was no longer available and thus the archived page was linked instead.

https://github.com/elastic/detection-rules/pull/3271

**Comment by terrancedejesus** [comment]
I have several PRs open to fix each branch.
Im going to double check all of the changes and merge them in, one by one. Should fix 7.10->main

**Comment by stiltz** [comment]
@terrancedejesus it looks like all the links are pointing to `http://` instead of `https://` and should probably be updated across the population of changes. I made a comment in the 7.10 update for this as well.

**Comment by terrancedejesus** [comment]
@stiltz - Updated all the links from 7.10 -> 8.11 and main. Then fixed the `http` to be `https`. Waiting for all PRs to finish the CI and pass. Then I will merge them all in. I referenced each to this PR for tracking purposes on either side.

**Comment by terrancedejesus** [comment]
All fixes have been implemented. @stiltz or @jmikell821 if there is nothing else, then we may be able to close this PR. Thanks again for bringing it to our attention!

**Comment by stiltz** [comment]
> All fixes have been implemented. @stiltz or @jmikell821 if there is nothing else, then we may be able to close this PR. Thanks again for bringing it to our attention!

Thank you. I'll close this with the fixes merged.

**Pull request closed without merging**
