### PR TITLE
[8.15] xMatters connector available for rule actions

### PR DESCRIPTION
**Pull request by nastasha-solomon**
Fixes https://github.com/elastic/security-docs/issues/5624

Previews:
- [Create a detection rule](https://security-docs_bk_5625.docs-preview.app.elstc.co/guide/en/security/master/rules-ui-create.html): Refreshed images that showed available rule action connectors

### CODE REVIEW

**Review by vitaliidm — APPROVED** [review]
We also add Server log in connectors.
But I don't see mentioning of xMatters anywhere in text, so should be fine for Server Log too

**Comment by nastasha-solomon** [comment]
Yeah, specific connectors aren't mentioned in the UI docs. Instead, the docs link users to the Kibana connector [docs](https://security-docs_bk_5625.docs-preview.app.elstc.co/guide/en/kibana/master/action-types.html) for more info on connectors that are available for rule actions.

**Review by joepeeples — APPROVED** [review]
LGTM, but I'd also challenge the idea that we need these screenshots at all. We end up having to update them all the time, and IMO they don't add a ton of value. They illustrate something that the user can very easily see themselves.

**Comment by nastasha-solomon** [comment]
@joepeeples yeah, I agree. I was actually thinking of removing the screenshot in ESS and Serverless docs when I update the 8.16 docs for case system actions. There are a couple of other minor changes that I need to make to the section anyways, so that'll be a good time to do some light cleanup.

**Pull request merged**
