### PR TITLE
Remove tech preview badges & page for serverless GA

### PR DESCRIPTION
**Pull request by joepeeples**
> [!IMPORTANT]
> Do not merge until Nov 20.

Resolves https://github.com/elastic/security-docs-internal/issues/41 by removing the "Technical Preview" badges at the top of every serverless docs page. Also removes the [Technical preview limitations](https://www.elastic.co/docs/current/serverless/security/security-technical-preview-limitations) page entirely.

# Previews
There's too many affected pages to check them all, but some spot-checking would be good. Link to the serverless docs:
https://security-docs_bk_5932.docs-preview.app.elstc.co/guide/en/serverless/current/what-is-security-serverless.html

### CODE REVIEW

**Comment by elasticdocs** [comment]
:rocket: Built _elastic-dot-co-docs-preview-docs_ successfully!

* https://elastic-dot-co-docs-production-akewqzqu2-elastic-dev.vercel.app

* Built with commit 80d57d72ded8ee608dcf4e777cfb8ba9d2589197

> Issues? Visit #next-docs in Slack

**Comment by colleenmcginnis** [comment]
@joepeeples I updated this PR to edit the serverless AsciiDoc files instead of the MDX files based on the changes made in #6061. Let me know if you have any questions!

**Comment by joepeeples** [comment]
Spot-checked the preview pages after the migration to AsciiDoc, and everything looks OK. This PR should be ready to approve and merge at the appointed time that we need to remove the badges.

**Comment by nastasha-solomon** [comment]
Recreated and merged in https://github.com/elastic/security-docs/pull/6187.

**Pull request closed without merging**
