### PR TITLE
[DOCS] Rename "Exceptions" page to "Exceptions lists"

### LINKED ISSUE #1479: [DOCS] Rename "Exceptions" page to "Exceptions lists"
## Description 

The "Exceptions" page is being renamed to "Exception lists" in `8.1`. Related tickets:

- PR: https://github.com/elastic/kibana/pull/124188
- Issue: https://github.com/elastic/kibana/issues/121756

Changes:
- Changes exceptions list page title from "Exceptions" to "Exception lists"
- Removes subheader
- Moves page update text to be where subheader was instead of top right

Screen Shot 2022-01-31 at 2 34 04 PM

## Affected Docs

- [x] https://www.elastic.co/guide/en/security/current/es-ui-overview.html#exceptions-page
- [x] https://www.elastic.co/guide/en/security/current/detections-ui-exceptions.html#manage-exceptions
- [x] Any other pages referencing the Exceptions page (text search of repo)
- [x] All screenshots that include the sidebar nav (spreadsheet for tracking)

### PR DESCRIPTION
**Pull request by joepeeples**
Resolves #1479 (based on https://github.com/elastic/kibana/pull/124188).

Previews:
* [Elastic Security UI](https://security-docs_1585.docs-preview.app.elstc.co/guide/en/security/master/es-ui-overview.html)
* [Hosts page overview](https://security-docs_1585.docs-preview.app.elstc.co/guide/en/security/master/hosts-overview.html)
* [Network page overview](https://security-docs_1585.docs-preview.app.elstc.co/guide/en/security/master/network-page-overview.html)
* [Anomaly Detection with Machine Learning](https://security-docs_1585.docs-preview.app.elstc.co/guide/en/security/master/machine-learning.html)
* [Rule exceptions and value lists | View and manage exception lists](https://security-docs_1585.docs-preview.app.elstc.co/guide/en/security/master/detections-ui-exceptions.html#manage-exceptions) - Topic where Exception lists page is actually documented. Other pages in this list are mostly screenshot updates.
* [Cases](https://security-docs_1585.docs-preview.app.elstc.co/guide/en/security/master/cases-overview.html)
* [Configure external connections](https://security-docs_1585.docs-preview.app.elstc.co/guide/en/security/master/cases-ui-integrations.html)
* [Trusted applications](https://security-docs_1585.docs-preview.app.elstc.co/guide/en/security/master/trusted-apps-ov.html)
* [Event filters](https://security-docs_1585.docs-preview.app.elstc.co/guide/en/security/master/event-filters.html)
* [Host isolation exceptions](https://security-docs_1585.docs-preview.app.elstc.co/guide/en/security/master/host-isolation-exceptions.html)
* [Experimental features | Host risk score](https://security-docs_1585.docs-preview.app.elstc.co/guide/en/security/master/host-risk-score.html)

### CODE REVIEW

**Review by yctercero — APPROVED** [review]
LGTM, thanks! Looks like you updated some snapshots so they don't include the side nav? That makes sense so they don't have to continuously be updated.

**Review by jmikell821 — APPROVED** [review]
LGTM - thanks!

**Review by nastasha-solomon — COMMENTED** [review]
Just two minor notes:
- I'll be updating the image for an open case (cases-ui-open.png) since cases will now have KPIs at the top. 
- It looks like the screenshot of the host risk score card (host-score-overview.png) on the Overview page is slightly outdated because it contains an old version of the Threat Intelligence card. Maybe we can stitch an image of the new card over the old one so we don't have to request a brand new screenshot from dev? Also, I believe this change will need to be backported to 7.16. Will check with the CTI team to verify.

**Review by nastasha-solomon — APPROVED** [review]

**Comment by joepeeples** [comment]
> Just two minor notes:
> 
> * I'll be updating the image for an open case (cases-ui-open.png) since cases will now have KPIs at the top.
> * It looks like the screenshot of the host risk score card (host-score-overview.png) on the Overview page is slightly outdated because it contains an old version of the Threat Intelligence card. Maybe we can stitch an image of the new card over the old one so we don't have to request a brand new screenshot from dev? Also, I believe this change will need to be backported to 7.16. Will check with the CTI team to verify.

Thanks! @nastasha-solomon and I discussed this: I'll merge this PR, then she will update these images separately; see history above for relevant issues.

**Pull request merged**
