### PR TITLE
[Request] Refresh screenshots and docs that describe the tabs on the Explore pages

### PR DESCRIPTION
**Pull request by nastasha-solomon**
Contributes to https://github.com/elastic/security-docs/issues/4784

Previews:
- [Elastic Security UI | Explore](https://security-docs_bk_4789.docs-preview.app.elstc.co/guide/en/security/master/es-ui-overview.html#_explore)
- [Hosts](https://security-docs_bk_4789.docs-preview.app.elstc.co/guide/en/security/master/hosts-overview.html#host-data-tables)
- [Network](https://security-docs_bk_4789.docs-preview.app.elstc.co/guide/en/security/master/network-page-overview.html#map-widgets-tables)
- [Users](https://security-docs_bk_4789.docs-preview.app.elstc.co/guide/en/security/master/users-page.html#_data_tables)
- [View and analyze risk score data | Alert triaging](https://security-docs_bk_4789.docs-preview.app.elstc.co/guide/en/security/master/analyze-risk-score-data.html#alert-triaging)

Twin Serverless PR: https://github.com/elastic/staging-serverless-security-docs/pull/290

### CODE REVIEW

**Review by semd — DISMISSED** [review]
LGTM!

**Comment by natasha-moore-elastic** [comment]
New screenshots LGTM!

It looks like the tab order has also changed on the host details and user details pages, but I will be updating those screenshots ([hosts-detail-pg.png](https://www.elastic.co/guide/en/security/current/images/hosts-detail-pg.png)) and ([user-details-pg.png](https://www.elastic.co/guide/en/security/current/images/users/user-details-pg.png)) as part of my Entity Analytics updates.

The [View and analyze risk score data](https://www.elastic.co/guide/en/security/current/analyze-risk-score-data.html) page also has some screenshots of the Host/User and host details/user details pages that need to be updated because of the new tab order (I won't be updating those in my PR since they don't show the features I'm documenting).

**Comment by nastasha-solomon** [comment]
Thanks for checking this and pointing out the additional screenshots that need to be refreshed, @natasha-moore-elastic! I might reach out this week for your help recreating the first two screenshots in the [Hosts and Users pages](https://www.elastic.co/guide/en/security/current/analyze-risk-score-data.html#hosts-users-pages) section since I don't have a deployment and project that's set up for screenshoting/testing risk score features at the moment.

**Comment by natasha-moore-elastic** [comment]
> Thanks for checking this and pointing out the additional screenshots that need to be refreshed, @natasha-moore-elastic! I might reach out this week for your help recreating the first two screenshots in the [Hosts and Users pages](https://www.elastic.co/guide/en/security/current/analyze-risk-score-data.html#hosts-users-pages) section since I don't have a deployment and project that's set up for screenshoting/testing risk score features at the moment.

Sure thing! I just had a look at a couple of our usual deployments, and `kibana.siem.estc.dev` seems best – risk scoring is enabled, and there's enough data to recreate those screenshots, but let me know if that doesn't work.

**Review by natasha-moore-elastic — APPROVED** [review]

**Pull request merged**
