### PR TITLE
Update threat-intel-integrations.asciidoc

### PR DESCRIPTION
**Pull request by tchen-tc**
New ThreatConnect Threat Intelligence integration  with  Elastic was released.

### CODE REVIEW

**Comment by nastasha-solomon** [comment]
Thanks for opening this, @tchen-tc! I'll take over the PR from here, and run the necessary technical and editorial reviews.

**Comment by tchen-tc** [comment]
@nastasha-solomon  Thank! Do I need to update this branch since it says it is out of date?

**Comment by nastasha-solomon** [comment]
Hey, @tchen-tc! 👋🏼 You're good! The page you updated needs to be fixed in other branches as well, so I'll likely close this PR and open a new one to re-apply the necessary changes to the appropriate areas in our docs.

**Comment by nastasha-solomon** [comment]
Applying this change in https://github.com/elastic/security-docs/pull/5338.

**Pull request closed without merging**
