### PR TITLE
[DOCS] Security telemetry settings

### PR DESCRIPTION
**Pull request by jmikell821**
Addresses #1099. 

Preview [here](https://security-docs_1157.docs-preview.app.elstc.co/guide/en/security/master/advanced-settings.html#telemetry-settings).

### CODE REVIEW

**Comment by stevewritescode** [comment]
@jmikell821 I see that this is still in draft. Does it need additional review from security data engineering or the PM team before merging?

**Comment by jmikell821** [comment]
@stevewritescode I would appreciate your review, and I was waiting to see from you or @SourinPaul if there were any more updates to the wording from the Google doc you included. If you two approve, I can merge this.

**Comment by stevewritescode** [comment]
Ok, I will re-review it once today or tomorrow and give you an explicit 👍

**Comment by stevewritescode** [comment]
Hi @jmikell821 - I updated some of the text in https://docs.google.com/document/d/10SjbucS3IyrN1SkRpQWexKhUx_uGS6cqV0SrKJe_Br4/edit. It's reviewed by engineering and ready to ship. @SourinPaul can you give a final 👍 ?

**Comment by SourinPaul** [comment]
@jmikell821 Steve's draft looks great to me as well. 

Sorry for dragging my feet on this.

**Review by SourinPaul — APPROVED** [review]
Changes look great. Thanks

**Review by stevewritescode — APPROVED** [review]
LGTM

**Pull request merged**
