### PR TITLE
[BUG] Old screenshot of Case Tab is mentioned in elastic guide

### PR DESCRIPTION
**Pull request by nastasha-solomon**
Addresses #731.

Preview [here](https://security-docs_746.docs-preview.app.elstc.co/guide/en/security/master/cases-overview.html).

### CODE REVIEW

**Comment by nastasha-solomon** [comment]
@elasticmachine run elasticsearch-ci/docs

**Review by jmikell821 — COMMENTED** [review]
LGTM - just one slight fix from what was published previously. Let's combined these two sentences into a single `NOTE:` I don't think them separated is necessary. 

image

**Comment by jmikell821** [comment]
@nastasha-solomon slight nits - in the note, change `"make sure"` --> `"ensure"`, and in the bulleted list at the bottom let's get rid of the period at the end of each list item. Then we can merge/backport after this, unless you'd like @karanbirsingh-qasource to review once more.

**Review by karanbirsingh-qasource — APPROVED** [review]
Required Changes are present in the shared guide .

Hence approving the pr request.

**Pull request merged**
